site: Hoanh An
url: https://hoanhan101.github.io/
author: Hoanh An
author:
  name: Hoanh An
  email: hoanhan101@gmai.com
  url: # url
  avatar: 
title: Hoanh An
description: Hoanh An's personal website
logo: 
image: 
twitter: # twitter 
twitter:
  username: # twitter
  creator: # twitter
  card: summary
social:
  name: Hoanh An
  links:
    - https://github.com/hoanhan101
    - https://www.linkedin.com/in/hoanhan101/
  
repository: hoanhan101/gray

permalink: pretty

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

disqus:
  name: "your username" # required
  noscript: "Please enable JavaScript to view the comments powered by Disqus." # optional

paginate:            10
paginate_path:       "/page/:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - disqus-for-jekyll
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-155884327-1
    anonymizeIp: false

collections:
  category:
    output: true
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  art:
    output: true
    permalink: /art/:slug
  
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/images"
    values:
      image: true
