#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

NOW=$(date +"%F")

FILE="_drafts/$NOW-$1.md"

echo "---
layout: post
title: Template's title
summary: Template's summary
category: Template
tags: [templates]
---

This is a template for you to copy from!" > "$FILE"

vi "$FILE"
