#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

NOW=$(date +"%F")

FILE="_posts/$NOW-$1.md"

echo "---
layout: post
title: TODO-title
summary: TODO-summary
category: TODO-template
tags: [TODO-tag]
---

This is a template for you to copy from!

<br>
**References:**
- [TODO-name](TODO-link)" > "$FILE"

vi "$FILE"
