#!/bin/sh

# If a command fails then the deploy stops.
set -e

printf "\033[0;32mDeploying updates to GitHub...\033[0m\n"

# Push changes from current directory first.
git push origin master

# Build the project.
JEKYLL_ENV=production bundle exec jekyll build

# Copy static site over local hoanhan101.github.io repo.
cp -R _site/. ../hoanhan101.github.io

# Save last commit message and hash.
msg=$(git log --format=%B -n 1 -1)
hash=$(git rev-parse HEAD)
msghash="${msg} (hoanhan101/gray@${hash})"

# Switch over and push those changes.
cd ../hoanhan101.github.io
git add .
git commit -m "$msghash"
git push origin master
